stages:
- prepare
- build
- test

variables:
  DOCKER_FILE: Dockerfile
  DOCKER_TAG: latest
  DOCKER_IMAGE: ${CI_REGISTRY_IMAGE}
  GIT_SUBMODULE_STRATEGY: normal


.prepare:docker: &prepare_docker
  stage: prepare
  image:
    name: quay.io/buildah/stable
  variables:
    _BUILDAH_STARTED_IN_USERNS: ""
    BUILDAH_ISOLATION: chroot
    BUILDAH_LAYERS: "true"
  before_script:
  - buildah version
  - buildah login --username "${CI_REGISTRY_USER}" --password "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
  script:
  - buildah bud -f ${DOCKER_FILE} -t ${DOCKER_IMAGE}:${DOCKER_TAG} .
  - buildah push ${DOCKER_IMAGE}:${DOCKER_TAG} docker://${DOCKER_IMAGE}:${DOCKER_TAG}
  after_script:
  - buildah logout "${CI_REGISTRY}"
  tags:
  - builder

prepare:docker:
  <<: *prepare_docker

build_demo:
  stage: build
  image: ${CI_REGISTRY_IMAGE}
  script:
    - cargo build -p rusty_demo
    - RUSTFLAGS="-Clinker-plugin-lto" cargo build -p rusty_demo --release
  cache:
    paths:
      - target/x86_64-unknown-hermit/debug/rusty_demo
      - target/x86_64-unknown-hermit/release/rusty_demo
    key: build-cache
  artifacts:
    paths:
      - target/x86_64-unknown-hermit/debug/rusty_demo
      - target/x86_64-unknown-hermit/release/rusty_demo

build_httpd:
  stage: build
  image: ${CI_REGISTRY_IMAGE}
  script:
    - cargo build -p httpd
    - RUSTFLAGS="-Clinker-plugin-lto" cargo build -p httpd --release
  cache:
    paths:
      - target/x86_64-unknown-hermit/debug/httpd
      - target/x86_64-unknown-hermit/release/httpd
    key: build-cache
  artifacts:
    paths:
      - target/x86_64-unknown-hermit/debug/httpd
      - target/x86_64-unknown-hermit/release/httpd

uhyve:
   stage: test
   needs: [build_demo]
   image: ${CI_REGISTRY_IMAGE}
   script:
     - lscpu
     - kvm-ok
     - ls /dev
     - uhyve -v -c 1 target/x86_64-unknown-hermit/debug/rusty_demo
     - uhyve -v -c 2 target/x86_64-unknown-hermit/debug/rusty_demo
     - uhyve -v -c 1 target/x86_64-unknown-hermit/release/rusty_demo
     - uhyve -v -c 2 target/x86_64-unknown-hermit/release/rusty_demo
   tags:
     - privileged
   cache:
     key: build-cache
     paths:
        - target/x86_64-unknown-hermit/debug/rusty_demo
        - target/x86_64-unknown-hermit/release/rusty_demo

qemu:
   stage: test
   needs: [build_demo]
   image: ${CI_REGISTRY_IMAGE}
   script:
     - lscpu
     - kvm-ok
     - ls /dev
     - cd loader
     - make
     - make release=1
     - cd ..
     - qemu-system-x86_64 -display none -smp 1 -m 64M -serial stdio -kernel loader/target/x86_64-unknown-hermit-loader/debug/rusty-loader -initrd target/x86_64-unknown-hermit/debug/rusty_demo -cpu host -enable-kvm
     - qemu-system-x86_64 -display none -smp 2 -m 64M -serial stdio -kernel loader/target/x86_64-unknown-hermit-loader/debug/rusty-loader -initrd target/x86_64-unknown-hermit/debug/rusty_demo -cpu host -enable-kvm
     - qemu-system-x86_64 -display none -smp 1 -m 64M -serial stdio -kernel loader/target/x86_64-unknown-hermit-loader/release/rusty-loader -initrd target/x86_64-unknown-hermit/release/rusty_demo -cpu host -enable-kvm
     - qemu-system-x86_64 -display none -smp 2 -m 64M -serial stdio -kernel loader/target/x86_64-unknown-hermit-loader/release/rusty-loader -initrd target/x86_64-unknown-hermit/release/rusty_demo -cpu host -enable-kvm
   tags:
     - privileged
   cache:
     key: build-cache
     paths:
        - target/x86_64-unknown-hermit/debug/rusty_demo
        - target/x86_64-unknown-hermit/release/rusty_demo
