language: rust
branches:
  only:
    # This is where pull requests from "bors r+" are built.
    - staging
    # This is where pull requests from "bors try" are built.
    - trying
    # Uncomment this to enable building pull requests.
    - master
rust:
  - nightly
services:
  - docker
os: linux
dist: bionic
cache: cargo
before_cache:
  # Only cache cargo dependencies, do a clean build for rusty-hermit
  - rm -rf $TRAVIS_BUILD_DIR/target
before_install:
  - sudo apt-get install -y qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils
  - sudo adduser $USER libvirt
  - sudo adduser $USER kvm
  - cargo install uhyve
  - docker pull registry.git.rwth-aachen.de/acs/public/hermitcore/hermitrust:latest 
  - >
    if [ $(egrep -c '(vmx|svm)' /proc/cpuinfo) -eq "0" ]; then
        echo "No virtualization possible - uhyve can't run";
        exit -1;
    fi
jobs:
  include:
    - name: "Test Debug Build"
      script:
        - docker run -v $PWD:/volume -e USER=$USER -w /volume --rm -t registry.git.rwth-aachen.de/acs/public/hermitcore/hermitrust cargo build -Z build-std=std,core,alloc,panic_abort --target x86_64-unknown-hermit
        # used to get terminal with new groups permissions while preserving own user
        - sudo -E sudo -u $USER -E bash -c "HERMIT_VERBOSE=1 $HOME/.cargo/bin/uhyve target/x86_64-unknown-hermit/debug/rusty_demo"
        - sudo -E sudo -u $USER -E bash -c "HERMIT_VERBOSE=1 HERMIT_CPUS=2 $HOME/.cargo/bin/uhyve target/x86_64-unknown-hermit/debug/rusty_demo"
    - name: "Test Release Build"
      script:
        - docker run -v $PWD:/volume -e USER=$USER -e RUSTFLAGS="-Clinker-plugin-lto" -w /volume --rm -t registry.git.rwth-aachen.de/acs/public/hermitcore/hermitrust cargo build -Z build-std=std,core,alloc,panic_abort --target x86_64-unknown-hermit --release
        - sudo -E sudo -u $USER -E bash -c "HERMIT_VERBOSE=1 $HOME/.cargo/bin/uhyve target/x86_64-unknown-hermit/release/rusty_demo"
        - sudo -E sudo -u $USER -E bash -c "HERMIT_VERBOSE=1 HERMIT_CPUS=2 $HOME/.cargo/bin/uhyve target/x86_64-unknown-hermit/release/rusty_demo"

