[package]
name = "hermit-abi"
version = "0.1.0"
authors = ["Stefan Lankes"]
license = "MIT/Apache-2.0"
readme = "README.md"
description = """
An interface between libstd and the unikernel RustyHermit and
is required for the `x86_64-unknown-hermit`
"""
keywords = ["unikernel", "libos"]
categories = ["os"]

[dependencies]
core = { version = "1.0.0", optional = true, package = "rustc-std-workspace-core" }
compiler_builtins = { version = "0.1.0", optional = true }
libc = { version = "0.2.51", default-features = false, features = ['rustc-dep-of-std'] }

[features]
docs = []
rustc-dep-of-std = ["core", "compiler_builtins/rustc-dep-of-std"]

[package.metadata.docs.rs]
features = ["docs"]
