[package]
name = "hermit-sys"
version = "0.1.0"
authors = ["Stefan Lankes"]
license = "MIT/Apache-2.0"
description = "FFI bindings to HermitCore"
repository = "https://github.com/hermitcore/rusty-hermit"
readme = "README.md"
keywords = ["unikernel", "libos"]
categories = ["os"]
links = "hermit"
build = "build.rs"
