[package]
name = "hermit-abi"
version = "0.1.4"
authors = ["Stefan Lankes"]
license = "MIT/Apache-2.0"
readme = "README.md"
description = """
hermit-abi is small interface to call functions from the unikernel RustyHermit.
It is used to build the target `x86_64-unknown-hermit`.
"""
repository = "https://github.com/hermitcore/rusty-hermit"
keywords = ["unikernel", "libos"]
categories = ["os"]

[dependencies]
core = { version = "1.0.0", optional = true, package = "rustc-std-workspace-core" }
compiler_builtins = { version = "0.1.0", optional = true }
libc = { version = "0.2.51", default-features = false }
hermit-sys = { path = "../hermit-sys", optional = true }

[features]
default = []
docs = []
with-libhermit = ["hermit-sys"]
rustc-dep-of-std = ["core", "compiler_builtins/rustc-dep-of-std", "libc/rustc-dep-of-std"]

[package.metadata.docs.rs]
features = ["docs"]
