name: Build docs

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-18.04 # linux required if you want to use docker
    container:
      image: registry.git.rwth-aachen.de/acs/public/hermitcore/hermitrust

    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        with:
         submodules: true
      - name: Generate documentation
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --workspace -Z build-std=std,core,alloc,panic_abort --target x86_64-unknown-hermit
      - name: Generate index.html
        run: |
          cat > target/x86_64-unknown-hermit/doc/index.html <<EOL
          <!doctype html>
          <html>
            <head>
              <title>Redirect!</title>
              <meta http-equiv="refresh" content="0; url=https://hermitcore.github.io/rusty-hermit/hermit_abi/" />
            </head>
            <body>
              <p><a href="https://hermitcore.github.io/rusty-hermit/hermit_abi/">Redirect</a></p>
            </body>
          </html>
          EOL
      - name: Deploy documentation
        if: success()
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: target/x86_64-unknown-hermit/doc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
