name: Tests with KVM support

on:
  pull_request:
  push:
    branches:
      - master
      - staging
      - trying
  schedule:
    - cron: '0 0 * * 6'

jobs:
  build:
    name: Test 
    runs-on: self-hosted
    steps:
    - name: Show OS infos
      run: |
          uname -a
    - name: Show KVM status
      run: |
          kvm-ok
