name: Tests with KVM support

on:
  push:
    branches:
      - master
      - staging
      - trying

jobs:
  build:
    name: Test 
    runs-on: self-hosted
    steps:
    - name: Show OS infos
      run: |
          uname -a
    #- name: Show KVM status
    #  run: |
    #      kvm-ok
